<?php

namespace Jobtech\LaravelChunky\Tests\Unit;

use Jobtech\LaravelChunky\ChunkySettings;
use Jobtech\LaravelChunky\Tests\TestCase;
use Illuminate\Contracts\Config\Repository;
use Jobtech\LaravelChunky\Handlers\MergeHandler;
use Jobtech\LaravelChunky\Exceptions\ChunkyException;

/**
 * @internal
 */
class ChunkySettingsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public static function indexProvider()
    {
        return [
            [null, ChunkySettings::INDEX_ZERO],
            [ChunkySettings::INDEX_ZERO, ChunkySettings::INDEX_ZERO],
            [ChunkySettings::INDEX_ONE, ChunkySettings::INDEX_ONE],
            [0, ChunkySettings::INDEX_ZERO],
            [1, ChunkySettings::INDEX_ONE],
            [10, 10],
        ];
    }

    /** @test */
    public function settingsHaveConfig()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->once()
                ->with('chunky')
                ->andReturn([
                    'foo' => 'bar',
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals(['foo' => 'bar'], $settings->config());
    }

    /** @test */
    public function settingsRetrieveDefaultDisk()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertNull($settings->chunksDisk());
        $this->assertNull($settings->mergeDisk());
    }

    /** @test */
    public function settingsRetrieveDefaultFolder()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEmpty($settings->chunksFolder());
        $this->assertEmpty($settings->mergeFolder());
    }

    /** @test */
    public function settingsRetrieveDefaultChunksDisk()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'disks' => [
                        'chunks' => [
                            'disk' => 'foo',
                        ],
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals('foo', $settings->chunksDisk());
    }

    /** @test */
    public function settingsRetrieveChunksFolder()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'disks' => [
                        'chunks' => [
                            'folder' => 'foo',
                        ],
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals('foo/', $settings->chunksFolder());
    }

    /** @test */
    public function settingsRetrieveDefaultMergeDisk()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'disks' => [
                        'merge' => [
                            'disk' => 'foo',
                        ],
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals('foo', $settings->mergeDisk());
    }

    /** @test */
    public function settingsRetrieveMergeFolder()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'disks' => [
                        'merge' => [
                            'folder' => 'foo',
                        ],
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals('foo/', $settings->mergeFolder());
    }

    /**
     * @test
     *
     * @dataProvider indexProvider
     *
     * @param $index
     * @param $expected
     */
    public function settingsRetrieveDefaultIndex($index, $expected)
    {
        $repository = $this->mock(Repository::class, function ($mock) use ($index) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'index' => $index,
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals($expected, $settings->defaultIndex());
    }

    /** @test */
    public function settingsRetrieveDefaultAdditionalChunksOptions()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals([], $settings->additionalChunksOptions());
    }

    /** @test */
    public function settingsRetrieveAdditionalChunksOptions()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'options' => [
                        'chunks' => [
                            'foo' => 'bar',
                        ],
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals(['foo' => 'bar'], $settings->additionalChunksOptions());
    }

    /** @test */
    public function settingsRetrieveDefaultAdditionalMergeOptions()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals([], $settings->additionalMergeOptions());
    }

    /** @test */
    public function settingsRetrieveAdditionalMergeOptions()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'options' => [
                        'merge' => [
                            'foo' => 'bar',
                        ],
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals(['foo' => 'bar'], $settings->additionalMergeOptions());
    }

    /** @test */
    public function settingsRetrieveDefaultAutoMergeOption()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertFalse($settings->autoMerge());
    }

    /** @test */
    public function settingsRetrieveAutoMergeOption()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'auto_merge' => true,
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertTrue($settings->autoMerge());
    }

    /** @test */
    public function settingsThrowsExceptionWithUndefinedMergeHandlerClass()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'merge' => [
                        'handler' => 'Foo\Bar\Baz',
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->expectException(ChunkyException::class);
        $settings->mergeHandler();
    }

    /** @test */
    public function settingsRetrieveMergeHandlerInstance()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'merge' => [
                        'handler' => MergeHandler::class,
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertInstanceOf(MergeHandler::class, $settings->mergeHandler());
    }

    /** @test */
    public function settingsRetrieveDefaultConnection()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertNull($settings->connection());
    }

    /** @test */
    public function settingsRetrieveConnection()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'merge' => [
                        'connection' => 'foo',
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals('foo', $settings->connection());
    }

    /** @test */
    public function settingsRetrieveDefaultQueue()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertNull($settings->queue());
    }

    /** @test */
    public function settingsRetrieveQueue()
    {
        $repository = $this->mock(Repository::class, function ($mock) {
            $mock->shouldReceive('get')
                ->with('chunky')
                ->once()
                ->andReturn([
                    'merge' => [
                        'queue' => 'foo',
                    ],
                ]);
        });

        $settings = new ChunkySettings($repository);

        $this->assertEquals('foo', $settings->queue());
    }
}
